/**
 * HAPI MCP server
 * Provides HAPI CLI specific tools including chat session title management
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { createServer } from "node:http";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { AddressInfo } from "node:net";
import { logger } from "@/ui/logger";
import { ApiSessionClient } from "@/api/apiSession";
import { randomUUID } from "node:crypto";
import { applyHapiTitleToMetadata, syncHapiMetadataTitleToCodexThread } from "@/codex/utils/codexThreadTitle";
import { buildAgentAttachments } from "./agentAttachment";
import {
    changeTitleInputSchema,
    HAPI_MCP_TOOL_NAMES,
    sendAttachmentInputSchema,
    type SendAttachmentInput
} from "./hapiMcpTools";

export async function startHappyServer(client: ApiSessionClient) {
    // Handler that sends title updates via the client
    const handler = async (title: string) => {
        logger.debug('[hapiMCP] Changing title to:', title);
        try {
            // Send title as a summary message, similar to title generator
            client.sendClaudeSessionMessage({
                type: 'summary',
                summary: title,
                leafUuid: randomUUID()
            });
            const metadata = client.getMetadataSnapshot();
            client.updateMetadata((currentMetadata) => applyHapiTitleToMetadata(currentMetadata, title));
            void syncHapiMetadataTitleToCodexThread(metadata ? applyHapiTitleToMetadata(metadata, title) : null);
            
            return { success: true };
        } catch (error) {
            return { success: false, error: String(error) };
        }
    };

    //
    // Create the MCP server
    //

    const mcp = new McpServer({
        name: "HAPI MCP",
        version: "1.0.0",
    });

    mcp.registerTool<any, any>('change_title', {
        description: 'Change the title of the current chat session',
        title: 'Change Chat Title',
        inputSchema: changeTitleInputSchema,
    }, async (args: { title: string }) => {
        const response = await handler(args.title);
        logger.debug('[hapiMCP] Response:', response);
        
        if (response.success) {
            return {
                content: [
                    {
                        type: 'text' as const,
                        text: `Successfully changed chat title to: "${args.title}"`,
                    },
                ],
                isError: false,
            };
        } else {
            return {
                content: [
                    {
                        type: 'text' as const,
                        text: `Failed to change chat title: ${response.error || 'Unknown error'}`,
                    },
                ],
                isError: true,
            };
        }
    });

    mcp.registerTool<any, any>('send_attachment', {
        description: [
            'Send files generated by the agent to the user as HAPI chat attachments.',
            'Use only for final user-facing artifacts that the user asked to receive.',
            'Each file path must be inside the current session working directory.'
        ].join(' '),
        title: 'Send Attachment',
        inputSchema: sendAttachmentInputSchema,
    }, async (args: SendAttachmentInput) => {
        try {
            const workingDirectory = client.getMetadataSnapshot()?.path
            if (!workingDirectory) {
                return {
                    content: [
                        {
                            type: 'text' as const,
                            text: 'Failed to send attachment: this session has no working directory.',
                        },
                    ],
                    isError: true,
                };
            }

            const attachments = await buildAgentAttachments(args.files, workingDirectory)
            client.sendAgentMessage({
                type: 'attachments',
                attachments
            })

            return {
                content: [
                    {
                        type: 'text' as const,
                        text: `Sent ${attachments.length} attachment${attachments.length === 1 ? '' : 's'} to the user.`,
                    },
                ],
                isError: false,
            };
        } catch (error) {
            return {
                content: [
                    {
                        type: 'text' as const,
                        text: `Failed to send attachment: ${error instanceof Error ? error.message : String(error)}`,
                    },
                ],
                isError: true,
            };
        }
    });

    const transport = new StreamableHTTPServerTransport({
        // NOTE: Returning session id here will result in claude
        // sdk spawn to fail with `Invalid Request: Server already initialized`
        sessionIdGenerator: undefined
    });
    await mcp.connect(transport);

    //
    // Create the HTTP server
    //

    const server = createServer(async (req, res) => {
        try {
            await transport.handleRequest(req, res);
        } catch (error) {
            logger.debug("Error handling request:", error);
            if (!res.headersSent) {
                res.writeHead(500).end();
            }
        }
    });

    const baseUrl = await new Promise<URL>((resolve) => {
        server.listen(0, "127.0.0.1", () => {
            const addr = server.address() as AddressInfo;
            resolve(new URL(`http://127.0.0.1:${addr.port}`));
        });
    });

    return {
        url: baseUrl.toString(),
        toolNames: [...HAPI_MCP_TOOL_NAMES],
        stop: () => {
            logger.debug('[hapiMCP] Stopping server');
            mcp.close();
            server.close();
        }
    }
}
